# Generated by Django 5.2.8 on 2025-11-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_expense_date_expense_note_expense_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='family_member',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('IN', 'Money In'), ('OUT', 'Money Out')], max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
